name: search_bar_sample1
description: "Description here"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/juneflow

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  beamer:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:
  super_cupertino_navigation_bar: #@add


dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view:  #@add
  june_view_more:  #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/search_bar_sample1/
  uses-material-design: true